name: Publish org.lflang to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
      - name: Publish package
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: org.lflang:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}